apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-audit-exporter
  labels:
    name: gatekeeper-audit-exporter
    enableMiscMetrics: "true"
spec:
  selector:
    control-plane: audit-controller
  ports:
    - name: aux
      port: 8888
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-controller-manager-exporter
  labels:
    name: gatekeeper-controller-manager-exporter
    enableMiscMetrics: "true"
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: aux
      port: 8888
      protocol: TCP
